import styles from "../../../panel.module.css";

const OK: Record<string, string> = {
  criado: "Produto criado.",
  salvo: "Alterações salvas.",
  publish: "Produto publicado.",
  unpublish: "Produto tirado da vitrine.",
  pause: "Venda pausada: o produto segue na vitrine como indisponível.",
  resume: "Venda retomada.",
  variante_pause: "Variante pausada.",
  variante_resume: "Variante retomada.",
  opcoes: "Opções salvas; variantes atualizadas.",
  adicionais: "Adicionais salvos.",
  evento: "Evento salvo.",
  lote_criado: "Lote criado; o estoque de ingressos foi contado.",
  lote_salvo: "Lote salvo.",
  lote_removido: "Lote removido.",
  entrega: "Entrega salva.",
  checkout: "Checkout salvo.",
  pagamento: "Meio de pagamento salvo.",
  pedido: "Pedido atualizado.",
  email: "Configuração de e-mail salva.",
  email_teste: "Teste enviado. Confira a caixa de entrada dessa conta.",
  despachado: "Etiqueta comprada. O cliente recebeu o código de rastreio.",
  cupom_criado: "Cupom criado.",
  cupom_salvo: "Cupom salvo.",
  devolucao: "Devolução registrada.",
  devolucao_approve: "Devolução aprovada.",
  devolucao_reject: "Devolução recusada.",
  devolucao_complete: "Devolução registrada com a evidência.",
  pagamento_testado: "Teste feito: veja o resultado no meio de pagamento.",
  arquivado: "Produto arquivado.",
  variante: "Variante atualizada.",
  imagem: "Imagem atualizada.",
  imagem_removida: "Imagem removida.",
  criada: "Categoria criada.",
  salva: "Categoria salva.",
  arquivada: "Categoria arquivada.",
  estoque: "Estoque atualizado.",
  minimo: "Nível mínimo salvo.",
  marca: "Marca salva.",
  seo: "SEO salvo.",
  landing: "Página inicial salva.",
  brief: "Respostas salvas.",
  proposta_pedida: "Pedido recebido: estamos montando a sua proposta.",
  proposta_publicada: "Proposta publicada: já está no ar.",
  proposta_descartada: "Proposta descartada.",
  legal: "Documento publicado.",
  acesso_approved: "Acesso liberado.",
  acesso_blocked: "Cliente bloqueado nesta loja.",
  acesso_revoked: "Acesso revogado.",
  dominio_criado: "Domínio cadastrado. Crie os registros de DNS mostrados abaixo.",
  dominio_conferido: "Conferência feita.",
  dominio_ativo: "DNS no ar: o domínio já responde pela sua loja.",
  dominio_principal: "Endereço principal atualizado.",
  dominio_desativado: "Domínio desativado.",
  envio_origem: "Endereço de origem salvo.",
  envio_regras: "Configuração de envio salva.",
  envio_servicos: "Serviços salvos: o checkout passa a mostrar só os marcados.",
  envio_conectado: "Conta da transportadora conectada.",
  envio_testado: "Teste feito: veja o resultado acima.",
  modulo_ligado: "Módulo ligado.",
  modulo_desligado: "Módulo desligado. Nada foi apagado.",
  vitrine: "Quem vê a vitrine foi atualizado.",
  taxa: "Repasse da taxa salvo.",
  embalagem_criada: "Embalagem cadastrada. Veja ao lado onde os seus produtos cabem.",
  embalagem_salva: "Embalagem salva.",
  embalagem_padrao: "Esta agora é a embalagem padrão da loja.",
  embalagem_arquivada: "Embalagem arquivada. Os produtos que só usavam ela passam para a escolha automática.",
  embalagem_reativada: "Embalagem reativada.",
  embalagem_apagada: "Embalagem apagada.",
  regras_embalagem: "Regras de embalagem salvas.",
};

const ERRORS: Record<string, string> = {
  validation_error: "Algum campo está inválido.",
  conflict: "Conflito com o estado atual (ex.: SKU/slug em uso ou produto sem imagem).",
  insufficient_stock: "Estoque insuficiente para essa saída.",
  permission_denied: "Seu papel não permite essa ação.",
  email_teste_falhou:
    "O servidor de e-mail recusou. Confira a conta e a senha de app, e tente de novo.",
  shipping_unavailable:
    "A transportadora não respondeu ou recusou. Tente de novo: etiqueta já comprada não é comprada outra vez.",
  confirmar_custo: "O frete subiu desde a compra. Marque \"Comprar mesmo com o frete mais caro\" para despachar.",
  shipping_insufficient_balance:
    "Sem saldo na carteira da transportadora. Recarregue e despache de novo.",
  shipment_in_progress: "O despacho deste pedido já está em andamento.",
  feature_disabled: "Esse módulo está desligado para a loja.",
  not_found: "Item não encontrado.",
  preco_obrigatorio: "Informe o preço.",
  preco_invalido: "Preço inválido (use 12,50).",
  quantidade_invalida: "Quantidade inválida (até 3 casas decimais).",
  data_invalida: "Data inválida.",
  cep_invalido: "Faixa de CEP inválida: use uma por linha, como 01000-000 a 01099-999.",
  numero_invalido: "Número inválido.",
  medida_invalida: "Medida ou peso inválido: use só números, sem unidade (ex.: 30 ou 30,5).",
  adicionais_invalidos: "Cada grupo precisa de nome e de uma linha por adicional, no formato Nome = 3,50.",
  escolha_produtos: "Escolha ao menos um produto para o bloco de destaques.",
  whatsapp_invalido: "WhatsApp inválido: escreva DDD + número (11 99999-9999).",
  instagram_invalido: "Instagram inválido: só o nome do perfil (letras, números, ponto ou _).",
  email_invalido: "E-mail inválido.",
  idempotency_in_progress: "Essa operação ainda está em andamento; aguarde.",
  invalid_transition: "Essa mudança não é possível a partir da situação atual.",
  pagamento_incompleto: "Faltam dados para ativar este meio de pagamento (veja o que falta abaixo).",
  stale_order: "O pedido mudou enquanto a tela estava aberta. Recarregue e tente de novo.",
  refund_too_large: "O valor passa do que ainda pode ser devolvido.",
  nothing_to_refund: "Não há pagamento aprovado para devolver neste pedido.",
  refund_state: "Esta devolução não está mais nessa situação.",
  four_eyes: "Quem pediu a devolução não pode aprová-la; peça a outra pessoa da loja.",
  motivo_obrigatorio: "Escreva o motivo (mínimo 3 caracteres).",
  codigo_invalido: "Código inválido: use letras, números, hífen ou _ (3 a 40).",
  percentual_invalido: "Porcentagem inválida (de 0 a 30).",
  coupon_code_taken: "Já existe um cupom com esse código.",
  evidencia_obrigatoria: "Descreva como a devolução foi feita (mínimo 10 caracteres).",
  rate_limited: "Muitas tentativas seguidas. Espere um minuto e tente de novo.",
  landing_ai_disabled: "A montagem com IA ainda não está disponível na sua loja.",
  landing_quota_exceeded: "Você já usou as propostas deste mês.",
  landing_draft_running: "Já há uma proposta sendo montada. Espere ela terminar.",
  landing_draft_not_ready: "Esta proposta ainda não está pronta.",
  landing_brief_empty: "Conte pelo menos o que a sua loja vende antes de pedir uma proposta.",
  instrucao_vazia: "Diga em uma frase o que você quer mudar.",
  cor_invalida: "Cor inválida.",
  credential_vault_unavailable: "O cofre de credenciais da plataforma está indisponível. Nada foi salvo — avise a MuhBianco.",
  integration_unavailable: "Serviço indisponível no momento. Nada foi salvo; tente de novo em alguns minutos.",
  dominio_invalido: "Domínio inválido. Escreva só o endereço, como loja.minhaempresa.com.br.",
  dns_sem_txt: "Ainda não encontrei o registro TXT. Depois de criar, o DNS pode levar alguns minutos.",
  module_not_self_service: "Este módulo é um serviço à parte: contrate na sua conta MuhBianco.",
  module_requires: "Ligue antes os módulos de que este depende.",
  module_in_use: "Outro módulo ligado depende deste; desligue aquele primeiro.",
  cep_origem_invalido: "CEP de origem inválido: informe os 8 dígitos.",
  token_invalido: "Token muito curto — confira se copiou inteiro.",
  peso_invalido: "Peso inválido: use só números (150 ou 1,2), e escolha g ou kg ao lado.",
  tipo_invalido: "Escolha o tipo da embalagem.",
  package_name_taken: "Já existe uma embalagem com esse nome.",
  package_limit: "A loja pode ter até 30 embalagens. Arquive ou apague uma antes.",
  default_package:
    "Com outras embalagens ativas, a padrão não pode ser arquivada nem apagada. Torne outra padrão antes.",
  package_in_use: "Há produtos que usam esta embalagem. Arquive em vez de apagar.",
  "conflict.package_inactive": "Embalagem arquivada não pode ser a padrão. Reative antes.",
  "conflict.package_conflict": "A embalagem mudou ao mesmo tempo em outra tela. Recarregue e tente de novo.",
  "validation_error.inner_required": "Informe as três medidas por dentro.",
  "validation_error.not_connected": "Conecte a conta da transportadora antes de escolher os serviços.",
  "validation_error.provider_unavailable": "A transportadora ainda não foi liberada para esta loja.",
  "validation_error.unknown_service": "Um dos serviços não está mais na sua conta. Recarregue a página e escolha de novo.",
  "validation_error.service_unavailable": "Um dos serviços está indisponível na sua conta agora.",
  servico_obrigatorio:
    "Marque pelo menos um serviço. Para parar de enviar por transportadora, desligue em Preço do frete.",
  "validation_error.tube_diameter": "No tubo, informe o comprimento e o diâmetro.",
  "validation_error.outer_partial": "Informe as três medidas por fora, ou deixe as três vazias.",
  "validation_error.outer_smaller": "A medida por fora não pode ser menor que a por dentro.",
  "validation_error.weight_limit": "O peso máximo precisa passar do peso da embalagem vazia.",
  packing_invalid: "Configuração de embalagem inválida.",
  "packing_invalid.duplicate_package": "A mesma embalagem foi escolhida duas vezes.",
  "packing_invalid.unknown_package": "Essa embalagem não existe mais. Recarregue a página.",
  "packing_invalid.own_container_needs_measures":
    "Para ir na embalagem dele, o produto precisa de peso e das três medidas.",
  "packing_invalid.own_container_not_flexible":
    "Produto flexível não vai na embalagem própria: ele precisa de uma caixa.",
  "packing_invalid.restricted_needs_packages": "Marque ao menos uma embalagem ativa para este produto.",
  "packing_invalid.too_compressed":
    "Essa quantidade faria o produto encolher para menos da metade. Diminua o número declarado.",
  "packing_invalid.does_not_fit": "Nem uma unidade cabe nessa embalagem. Desmarque-a ou confira as medidas.",
  "packing_invalid.too_heavy": "Essa quantidade passa do peso que a embalagem aguenta.",
  "packing_invalid.missing_measures": "Para declarar quantos cabem, informe peso e medidas do produto.",
  dns_falta_apontar: "Posse confirmada, mas o domínio ainda não aponta para a MuhBianco. Confira o CNAME (ou o A, no domínio raiz).",
};

export function Flash({ ok, erro }: { ok?: string; erro?: string }) {
  if (erro) {
    // `codigo.motivo` (ex.: packing_invalid.too_compressed): a frase do motivo, senão a do código.
    const message = ERRORS[erro] ?? ERRORS[erro.split(".")[0] ?? erro] ?? `Não foi possível salvar (${erro}).`;
    return <p className={styles.error}>{message}</p>;
  }
  if (ok && OK[ok]) return <p className={styles.ok}>{OK[ok]}</p>;
  return null;
}
