import styles from "../../../panel.module.css";

const OK: Record<string, string> = {
  criado: "Produto criado.",
  salvo: "Alterações salvas.",
  publish: "Produto publicado.",
  unpublish: "Produto tirado da vitrine.",
  pause: "Venda pausada: o produto segue na vitrine como indisponível.",
  resume: "Venda retomada.",
  variante_pause: "Variante pausada.",
  variante_resume: "Variante retomada.",
  opcoes: "Opções salvas; variantes atualizadas.",
  adicionais: "Adicionais salvos.",
  evento: "Evento salvo.",
  lote_criado: "Lote criado; o estoque de ingressos foi contado.",
  lote_salvo: "Lote salvo.",
  lote_removido: "Lote removido.",
  entrega: "Entrega salva.",
  checkout: "Checkout salvo.",
  pagamento: "Meio de pagamento salvo.",
  pedido: "Pedido atualizado.",
  cupom_criado: "Cupom criado.",
  cupom_salvo: "Cupom salvo.",
  devolucao: "Devolução registrada.",
  devolucao_approve: "Devolução aprovada.",
  devolucao_reject: "Devolução recusada.",
  devolucao_complete: "Devolução registrada com a evidência.",
  pagamento_testado: "Teste feito: veja o resultado no meio de pagamento.",
  arquivado: "Produto arquivado.",
  variante: "Variante atualizada.",
  imagem: "Imagem atualizada.",
  imagem_removida: "Imagem removida.",
  criada: "Categoria criada.",
  salva: "Categoria salva.",
  arquivada: "Categoria arquivada.",
  estoque: "Estoque atualizado.",
  minimo: "Nível mínimo salvo.",
  marca: "Marca salva.",
  seo: "SEO salvo.",
  landing: "Página inicial salva.",
  legal: "Documento publicado.",
  acesso_approved: "Acesso liberado.",
  acesso_blocked: "Cliente bloqueado nesta loja.",
  acesso_revoked: "Acesso revogado.",
  dominio_criado: "Domínio cadastrado. Crie os registros de DNS mostrados abaixo.",
  dominio_conferido: "Conferência feita.",
  dominio_ativo: "DNS no ar: o domínio já responde pela sua loja.",
  dominio_principal: "Endereço principal atualizado.",
  dominio_desativado: "Domínio desativado.",
};

const ERRORS: Record<string, string> = {
  validation_error: "Algum campo está inválido.",
  conflict: "Conflito com o estado atual (ex.: SKU/slug em uso ou produto sem imagem).",
  insufficient_stock: "Estoque insuficiente para essa saída.",
  permission_denied: "Seu papel não permite essa ação.",
  feature_disabled: "Esse módulo está desligado para a loja.",
  not_found: "Item não encontrado.",
  preco_obrigatorio: "Informe o preço.",
  preco_invalido: "Preço inválido (use 12,50).",
  quantidade_invalida: "Quantidade inválida (até 3 casas decimais).",
  data_invalida: "Data inválida.",
  cep_invalido: "Faixa de CEP inválida: use uma por linha, como 01000-000 a 01099-999.",
  numero_invalido: "Número inválido.",
  adicionais_invalidos: "Cada grupo precisa de nome e de uma linha por adicional, no formato Nome = 3,50.",
  escolha_produtos: "Escolha ao menos um produto para o bloco de destaques.",
  whatsapp_invalido: "WhatsApp inválido: escreva DDD + número (11 99999-9999).",
  instagram_invalido: "Instagram inválido: só o nome do perfil (letras, números, ponto ou _).",
  email_invalido: "E-mail inválido.",
  idempotency_in_progress: "Essa operação ainda está em andamento; aguarde.",
  invalid_transition: "Essa mudança não é possível a partir da situação atual.",
  pagamento_incompleto: "Faltam dados para ativar este meio de pagamento (veja o que falta abaixo).",
  stale_order: "O pedido mudou enquanto a tela estava aberta. Recarregue e tente de novo.",
  refund_too_large: "O valor passa do que ainda pode ser devolvido.",
  nothing_to_refund: "Não há pagamento aprovado para devolver neste pedido.",
  refund_state: "Esta devolução não está mais nessa situação.",
  four_eyes: "Quem pediu a devolução não pode aprová-la; peça a outra pessoa da loja.",
  motivo_obrigatorio: "Escreva o motivo (mínimo 3 caracteres).",
  codigo_invalido: "Código inválido: use letras, números, hífen ou _ (3 a 40).",
  percentual_invalido: "Porcentagem inválida (de 0,01 a 100).",
  coupon_code_taken: "Já existe um cupom com esse código.",
  evidencia_obrigatoria: "Descreva como a devolução foi feita (mínimo 10 caracteres).",
  rate_limited: "Muitas tentativas seguidas. Espere um minuto e tente de novo.",
  dominio_invalido: "Domínio inválido. Escreva só o endereço, como loja.minhaempresa.com.br.",
  dns_sem_txt: "Ainda não encontrei o registro TXT. Depois de criar, o DNS pode levar alguns minutos.",
  dns_falta_apontar: "Posse confirmada, mas o domínio ainda não aponta para a MuhBianco. Confira o CNAME (ou o A, no domínio raiz).",
};

export function Flash({ ok, erro }: { ok?: string; erro?: string }) {
  if (erro) {
    return <p className={styles.error}>{ERRORS[erro] ?? `Não foi possível salvar (${erro}).`}</p>;
  }
  if (ok && OK[ok]) return <p className={styles.ok}>{OK[ok]}</p>;
  return null;
}
